### ISSUE TITLE
Users

### ISSUE THREAD

**Issue by Nicanor008** [Nicanor008/shoman-FE#23]
As a mentor, I want to view;
- [ ] My personal details
- [ ] My mentee(s) details
- [ ] View all mentees

As a mentee, I want to view;
- [ ] My personal details
- [ ] My mentor details
- [ ] View my teammates

As a super-admin, I wan to view;
- [ ] All users in the systems
- [ ] All mentees
- [ ] All mentors

Added Functionality to mentors & mentees
- [ ] Update account
- [ ] Request to be deactivated/deleted

### User details will refer to:
Email, first name, last name, data joined, role, stack, active/inactive status

### Task Description
<img width="1095" alt="Screenshot 2020-11-03 at 22 23 37" src="https://user-images.githubusercontent.com/25298492/98031472-98bace00-1e23-11eb-958b-daf573936251.png">

### Designs
<img width="484" alt="Screenshot 2020-11-03 at 22 27 40" src="https://user-images.githubusercontent.com/25298492/98031639-d61f5b80-1e23-11eb-8220-2382e1a005f9.png">

**Comment by Nyakaru** [comment]
@Nicanor008 Please assign @samimbugwa this issue

**Comment by Nicanor008** [comment]
> @Nicanor008 Please assign @samimbugwa this issue

I can't find Sammy in Github. Can he just clone this repo and assign himself
<img width="382" alt="Screenshot 2020-11-18 at 10 42 55" src="https://user-images.githubusercontent.com/25298492/99500119-efc7b380-298a-11eb-8cf9-338a8b5dc07b.png">
